CREATE DATABASE HANGFIRE
GO
USE HANGFIRE
GO

EXEC sp_configure 'CONTAINED DATABASE AUTHENTICATION', 1
GO
RECONFIGURE
GO
ALTER DATABASE [HANGFIRE] SET CONTAINMENT = PARTIAL
GO


CREATE USER [HangFire] WITH PASSWORD = 'Secret@1234'
GO
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE [name] = 'HangFire') EXEC ('CREATE SCHEMA [HangFire]')
GO
ALTER AUTHORIZATION ON SCHEMA::[HangFire] TO [HangFire]
GO
GRANT CREATE TABLE TO [HangFire]
GO

